// flow-typed signature: cbfb2f88f5a6e248e05417d60052b361
// flow-typed version: <<STUB>>/gorun_v^0.4.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gorun'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gorun' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gorun/bin/gorun-exec' {
  declare module.exports: any;
}

declare module 'gorun/build' {
  declare module.exports: any;
}

declare module 'gorun/bundle' {
  declare module.exports: any;
}

declare module 'gorun/clean' {
  declare module.exports: any;
}

declare module 'gorun/copy' {
  declare module.exports: any;
}

declare module 'gorun/gorun-config' {
  declare module.exports: any;
}

declare module 'gorun/run' {
  declare module.exports: any;
}

declare module 'gorun/transform-babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gorun/bin/gorun-exec.js' {
  declare module.exports: $Exports<'gorun/bin/gorun-exec'>;
}
declare module 'gorun/build.js' {
  declare module.exports: $Exports<'gorun/build'>;
}
declare module 'gorun/bundle.js' {
  declare module.exports: $Exports<'gorun/bundle'>;
}
declare module 'gorun/clean.js' {
  declare module.exports: $Exports<'gorun/clean'>;
}
declare module 'gorun/copy.js' {
  declare module.exports: $Exports<'gorun/copy'>;
}
declare module 'gorun/gorun-config.js' {
  declare module.exports: $Exports<'gorun/gorun-config'>;
}
declare module 'gorun/run.js' {
  declare module.exports: $Exports<'gorun/run'>;
}
declare module 'gorun/transform-babel.js' {
  declare module.exports: $Exports<'gorun/transform-babel'>;
}
